#+TITLE: Emacs Doom Config
#+AUTHOR: Daniel Berio
#+EMAIL: drand48@gmail.com
#+PROPERTY: header-args :emacs-lisp :tangle yes :cache yes :results silent :comments link :exports code

To execute all and update use ~C-c C-v b~ or ~C-c C-v C-b~ or ~M-x
org-babel-execute-buffer~
Or ~M-x doom/reload~

**NB.** For a literate config to work you need to set the ~literate~ flag in ~init.el~

Doom keybindings ref:
- https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el

** Configuration rabbithole links
- [[https://tecosaur.github.io/emacs-config/config.html][Techosaur: Very long nice config]]
- https://github.com/hjertnes/emacs.d/blob/master/hjertnes.org

*** Install on Ubuntu
Note that Ubuntu needs "modules" support, best way to install seems to follow these instructions:
- [[http://ubuntuhandbook.org/index.php/2019/02/install-gnu-emacs-26-1-ubuntu-18-04-16-04-18-10][Link]]

#+begin_example
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt update
sudo apt install emacs26
#+end_example

** General
Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.

#+begin_src emacs-lisp
(setq user-full-name "Daniel Berio"
      user-mail-address "drand48@gmail.com")
#+end_src

Start emacs with a maximized window
#+begin_src emacs-lisp
;(add-hook 'window-setup-hook 'toggle-frame-maximized t)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

Do not keep undo history after quit (see [[https://github.com/hlissner/doom-emacs/issues/1407][this]]).
#+begin_src emacs-lisp
;; Don't save undo-tree history
(after! undo-tree
  (setq undo-tree-auto-save-history nil))
#+end_src

Counsel-grep for big files
#+begin_src emacs-lisp
(setq counsel-grep-base-command "rg -S -M 120 --no-heading --line-number --color never %s %s")
#+end_src

Force damn delete selection?
See [[https://gitlab.com/justinekizhak/dotfiles/blob/master/emacs/doom.d/config.org][this]]
#+begin_src emacs-lisp
(use-package delsel
  :disabled
  :ensure nil
  :config (delete-selection-mode +1))

(setq delete-selection-mode t)
#+end_src

Use CUA mode since I'm also using other editors
#+begin_src emacs-lisp
(cua-mode +1)
#+end_src

#+begin_src emacs-lisp
(use-package flyspell
  :ensure t
  :config
  (setq ispell-program-name "/usr/local/bin/aspell"
        ispell-dictionary "english"))
#+end_src

#+begin_src emacs-lisp
#+end_src

** Figlet
Because I like ascii text. From [https://github.com/emacsmirror/figlet/blob/master/figlet.el]
Type ~M-x figlet~ and you will be asked for a string. If you use a prefix ~C-u
M-x figlet~ it will ask for a font.
#+begin_src emacs-lisp
(load! "~/.doom.d/figlet/figlet.el")
(setq figlet-font-dir "~/.doom.d/figlet/fonts")
(setq figlet-default-font "computer")
#+end_src

** Editor
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

#+begin_src emacs-lisp
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
#+end_src


They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:

#+begin_src emacs-lisp
;(setq doom-font (font-spec :family "monospace" :size 14))
(setq doom-font (font-spec :family "Fira Code" :size 13))
#+end_src


There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
~load-theme~~ function. This is the default:

#+begin_src emacs-lisp
;(setq doom-theme 'doom-one)
;(setq doom-theme 'doom-laserwave) ; kinda nice
;(setq doom-theme 'doom-zenburn) ; kinda nice
;(setq doom-theme 'doom-wilmersorf) ; kinda nice
(setq doom-theme 'doom-snazzy) ; kinda nice
;(setq doom-theme 'doom-rouge) ; kinda nice maybe
;(setq doom-theme 'doom-nord)
;(load-theme 'doom-snazzy)
#+end_src

This determines the style of line numbers in effect. If set to ~nil~, line
numbers are disabled. For relative line numbers, set this to ~relative~.
#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

No menu bar
#+begin_src emacs-lisp
(menu-bar-mode -1)
#+end_src

*** Key-bindings etc
#+begin_src emacs-lisp
; (evil-multiedit-default-keybinds)
#+end_src

#+begin_src emacs-lisp
;(global-set-key (kbd "C-y") 'yank)
(global-set-key (kbd "s-z") 'undo-tree-undo)
(global-set-key (kbd "s-Z") 'undo-tree-redo)
(global-set-key (kbd "s-v") 'yank)
(global-set-key (kbd "s-c") 'evil-yank)
(global-set-key (kbd "s-a") 'mark-whole-buffer)
(global-set-key (kbd "s-x") 'kill-region)
(global-set-key (kbd "s-s") 'save-buffer)
(global-set-key (kbd "s-s") 'save-buffer)

(define-key evil-insert-state-map (kbd "C-e") 'move-end-of-line)
(define-key evil-insert-state-map (kbd "C-k") 'kill-line)
(define-key evil-insert-state-map (kbd "C-w") 'kill-region)
(define-key evil-visual-state-map (kbd "C-e") 'move-end-of-line)
(define-key evil-normal-state-map (kbd "C-e") 'move-end-of-line)
(define-key evil-normal-state-map (kbd "C-k") 'kill-line)
(define-key evil-normal-state-map (kbd "C-y") 'yank)
(define-key evil-insert-state-map (kbd "C-y") 'yank)
(define-key evil-normal-state-map (kbd "C-w") 'kill-region)
(define-key evil-visual-state-map (kbd "C-w") 'kill-region)

; I fins some of these evil key-bindings are really odd...
(define-key evil-insert-state-map (kbd "C-x C-s") 'save-buffer)


;; (map!
;;  "C-a"     #'move-beginning-of-line
;;  "C-e"      #'move-end-of-line
;;  )
#+end_src
Counsel: Use ~SPC-~~ followed by char

#+begin_src emacs-lisp
;; (map! :leader
;;       (:prefix "m"
;;         :desc "Ivy citation" "i"  #'ivy-bibtex-with-local-bibliography
;;         :desc "Reftex citation" "r"  #'reftex-citation
;;         ;:desc "figlet" "f" #("figlet")
;;         ;:desc "text" "f f" #'figlet
;;         ;:desc "comment" "f c" #'figlet-comment
;;         ))
#+end_src

Some key bindings I am used to, but this is not working in Doom...
#+begin_src emacs-lisp
;; Use C-u, C-d also in insert mode
(global-set-key (kbd "C-u") nil)
(global-set-key (kbd "C-d") nil)
(global-set-key (kbd "C-u") 'evil-scroll-up)
(global-set-key (kbd "C-d") 'evil-scroll-down)
(global-set-key (kbd "C-e") 'move-end-of-line)
#+end_src

Always support shift selec and delete
#+begin_src emacs-lisp
;; Delete selection
(setq delete-selection-mode t)
(setq shift-select-mode t)
#+end_src

Windmove (move among windows), not ideal but trying to mangle too many
key-bindings on Windows/WSL setup, where super and alt are taken mostly.
#+begin_src emacs-lisp
(global-set-key (kbd "C-q") nil)
(global-set-key (kbd "C-q <left>")  'windmove-left)
(global-set-key (kbd "C-q <right>") 'windmove-right)
(global-set-key (kbd "C-q <up>")    'windmove-up)
(global-set-key (kbd "C-q <down>")  'windmove-down)
#+end_src
*** Look and feel
#+begin_src emacs-lisp
(use-package! dimmer
  :config (dimmer-mode))
#+end_src
** Notes from doom config
Here are some additional functions/macros that could help you configure Doom:

 - ~load!~ for loading external *.el files relative to this one
 - ~use-package~ for configuring packages
 - ~after!~ for running code after a package has loaded
 - ~add-load-path!~ for adding directories to the `load-path', relative to
   this file. Emacs searches the ~load-path~ when you load packages with
   ~require~ or ~use-package~.
 - ~map!~ for binding new keys

 To get information about any of these functions/macros, move the cursor over
 the highlighted symbol at press 'K' (non-evil users must press 'C-c g k').
 This will open documentation for it, including demos of how they are used.


You can also try ~gd~ (or ~C-c g d~) to jump to their definition and see how
they are implemented.

** Org mode customizations

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org ~loads!~

#+begin_src emacs-lisp
(setq org-directory "~/Dropbox/org/")
#+end_src

Enable shift select in org mode
#+BEGIN_SRC emacs-lisp
(setq org-support-shift-select 'always)
#+END_SRC

Embed CSS by default

#+begin_src emacs-lisp
(defun my-org-inline-css-hook (exporter)
  "Insert custom inline css"
  (when (eq exporter 'html)
    (let* ((dir (ignore-errors (file-name-directory (buffer-file-name))))
           (path (concat dir "style.css"))
           (homestyle (or (null dir) (null (file-exists-p path))))
           (final (if homestyle "~/.doom.d/org-style.css" path))) ;; <- set your own style file path
      (setq org-html-head-include-default-style nil)
      (setq org-html-head (concat
                           "<style type=\"text/css\">\n"
                           "<!--/*--><![CDATA[/*><!--*/\n"
                           (with-temp-buffer
                             (insert-file-contents final)
                             (buffer-string))
                           "/*]]>*/-->\n"
                           "</style>\n")))))

(add-hook 'org-export-before-processing-hook 'my-org-inline-css-hook)
#+end_src

Setup org-ref

#+begin_src emacs-lisp

;; Big hack to insert biblio entry titles
;; unelegant simply because I do not really know LISP
;; adapted from: http://www.mail-archive.com/emacs-orgmode@gnu.org/msg110385.html

(defun set-format (key)
  (setf (cdr (assoc key (cdr (assoc "org"
                                    org-ref-formatted-citation-formats))))
        "${author} ${year}. /${title}/. [[cite:${=key=}]]")
  )

(use-package! org-ref
    :after org
    :init
    ; code to run before loading org-ref
    :config
    ; code to run after loading org-ref
    (setq org-ref-default-bibliography '("./autograff-biblio.bib")) ; this is a list but multiple files don't seem to work
    (setq org-ref-formatted-citation-backend "org")
    (set-format "article")
    (set-format "inproceedings")
    (set-format "book")
    (set-format "phdthesis")
    (set-format "inbook")
    (set-format "incollection")
    (set-format "proceedings")
    (set-format "unpublished")

    )
#+end_src

Also for some reason "phdthesis" is not included in the version of bibtex used
here. Adapted from [[https://github.com/eush77/dotfiles/blob/fede630f5ad677af9e4294b6549e1ff4ed9bfc15/emacs/.emacs.d/config/config-bibtex.el][here]]
#+begin_src emacs-lisp
(defvar my-bibtex-biblatex-entry-type-special-aliases
  '(("Thesis"
     ("MastersThesis" "Master's Thesis")
     ("PhdThesis" "PhD Thesis"))
    ("Report"
     ("TechReport" "Technical Report")))
  "Special entry type aliases specified in BibLaTeX.")

(after! bibtex
;; Add special entry type aliases.
(pcase-dolist (`(,aliasee . ,aliases)
               my-bibtex-biblatex-entry-type-special-aliases)
  (pcase-let ((`(_ _ ,required nil ,optional)
               (assoc aliasee bibtex-biblatex-entry-alist)))
    (dolist (alias aliases)
      (add-to-list 'bibtex-biblatex-entry-alist
                   (append alias
                           (list (remove '("type") required)
                                 nil
                                 (cons '("type") optional)))))))

(bibtex-set-dialect 'biblatex)
)
#+end_src
#+begin_src emacs-lisp
;; (use-package! helm-bibtex
;;   :config
;;   (setq helm-bibtex-bibliography '("./autograff-biblio.bib"))
;; )
#+end_src

Setup org to open Zotero links
#+BEGIN_SRC emacs-lisp
;; Create hyperlink on export
(defun zotero-org-export (link description format)
  (let ((path (concat "zotero:" link))
        (desc (or description "Open in Zotero")))
    (pcase format
      (`html (format "<a target=\"_blank\" href=\"%s\">%s</a>" path desc))
      (`latex (format "\\href{%s}{%s}" path desc))
      (`texinfo (format "@uref{%s,%s}" path desc))
      (`ascii (format "%s (%s)" desc path))
      (t path))))
;; Setup links
(add-hook 'org-mode-hook
          (lambda ()
(org-add-link-type "zotero"
                   (lambda (path)
                              (browse-url (concat "zotero:" path)))
                   'zotero-org-export)))
#+END_SRC

Preview latex on save ([[https://emacs.stackexchange.com/questions/38198/automatically-preview-latex-in-org-mode-as-soon-as-i-finish-typing][from]])
#+begin_src emacs-lisp
;; (defun my/org-render-latex-fragments ()
;;   (if (org-list-latex-overlays)
;;       (progn (org-toggle-latex-fragment)
;;              (org-toggle-latex-fragment))
;;     (org-toggle-latex-fragment)))

;; (add-hook 'org-mode-hook
;;           (lambda ()
;;             (add-hook 'after-save-hook 'my/org-render-latex-fragments nil 'make-the-hook-local)))
#+end_src
Counsel key-bindings
#+begin_src emacs-lisp
(map!
 :after org
 :map org-mode-map
 :leader
      (:prefix "m"
        :desc "Insert citation" "i"  #'org-ref-helm-insert-cite-link
        ))
#+end_src

Also org mode resets the ~delete-selection-mode~. TODO find a better solution to this
#+begin_src emacs-lisp
(add-hook 'org-mode-hook '(lambda () (setq delete-selection-mode t)))
#+end_src

Preview latex fragments when cursor is elsewhere
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-fragtog-mode)
#+end_src

#+begin_src emacs-lisp
'(org-preview-latex-process-alist
       (quote
       ((dvipng :programs
         ("lualatex" "dvipng")
         :description "dvi > png" :message "you need to install the programs: latex and dvipng." :image-input-type "dvi" :image-output-type "png" :image-size-adjust
         (1.0 . 1.0)
         :latex-compiler
         ("lualatex -output-format dvi -interaction nonstopmode -output-directory %o %f")
         :image-converter
         ("dvipng -fg %F -bg %B -D %D -T tight -o %O %f"))
 (dvisvgm :programs
          ("latex" "dvisvgm")
          :description "dvi > svg" :message "you need to install the programs: latex and dvisvgm." :use-xcolor t :image-input-type "xdv" :image-output-type "svg" :image-size-adjust
          (1.7 . 1.5)
          :latex-compiler
          ("xelatex -no-pdf -interaction nonstopmode -output-directory %o %f")
          :image-converter
          ("dvisvgm %f -n -b min -c %S -o %O"))
 (imagemagick :programs
              ("latex" "convert")
              :description "pdf > png" :message "you need to install the programs: latex and imagemagick." :use-xcolor t :image-input-type "pdf" :image-output-type "png" :image-size-adjust
              (1.0 . 1.0)
              :latex-compiler
              ("xelatex -no-pdf -interaction nonstopmode -output-directory %o %f")
              :image-converter
              ("convert -density %D -trim -antialias %f -quality 100 %O")))))
#+end_src
#+begin_src emacs-lisp
(use-package! cdlatex
    :after (:any org-mode LaTeX-mode)
    :hook
    ((LaTeX-mode . turn-on-cdlatex)
     (org-mode . turn-on-org-cdlatex)))

(use-package! company-math
    :after (:any org-mode TeX-mode)
    :config
    (set-company-backend! 'org-mode 'company-math-symbols-latex)
    (set-company-backend! 'TeX-mode 'company-math-symbols-latex)
    (set-company-backend! 'org-mode 'company-latex-commands)
    (set-company-backend! 'TeX-mode 'company-latex-commands)
    (setq company-tooltip-align-annotations t)
    (setq company-math-allow-latex-symbols-in-faces t))
#+end_src

** Magit
Performance improvements
#+begin_src emacs-lisp
(use-package! magit
    :config
    ; code to run after loading magit
    (setq magit-commit-show-diff nil)
    (setq magit-revert-buffers 1)
    )
#+end_src
Do not show whitespace diffs

#+begin_src emacs-lisp
(setq ediff-diff-options "-w")
#+end_src
** Latex (AucTex + RefTex)


And set pdf-tools internal latex viewer
#+begin_src emacs-lisp
;(setenv "PKG_CONFIG_PATH" (concat (shell-command-to-string "printf %s \"$(brew --prefix libffi)\"") "/lib/pkgconfig/"))
#+end_src

#+begin_src emacs-lisp
(setq +latex-viewers '(pdf-tools))
#+end_src

From doom issues, sync latex and pdf, still bit dodgy:
#+begin_src emacs-lisp
;; to use pdfview with auctex
 (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
    TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
    TeX-source-correlate-start-server t) ;; not sure if last line is neccessary
#+end_src


Trying to get rid of the ~epdfinfo: Destination not found~ error.
See [https://github.com/politza/pdf-tools/issues/302]
#+begin_src emacs-lisp
(add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
#+end_src

Ask for master file (~Tex-master~ multifile support)? Ideally we would want
AucTex to always ask (~nil~), but this is set in the local variables of a buffer
(~C-c n~ to reset). Also seems that manually setting the variable (at the end of
the doc) does not work, so it needs to be done with ~C-c _~ at least on Mac.
#+begin_src emacs-lisp
(add-hook 'LaTeX-mode-hook
          (setq-default TeX-master t))
#+end_src


Get RefTex to search for valid biblios
#+begin_src emacs-lisp
(setq reftex-use-external-file-finders t)
#+end_src

Setting up IVY bibtex
#+begin_src emacs-lisp
;(setq ivy-bibtex-default-action 'ivy-bibtex-insert-key)
#+end_src

When Option-clicking on text, jump to pdf position.
#+begin_src emacs-lisp
(with-eval-after-load "latex"
  (define-key LaTeX-mode-map [M-down-mouse-1] 'pdf-sync-forward-search))
#+end_src

#+begin_src emacs-lisp
;; Using pdflatex as the default compiler for .tex files
(setq latex-run-command "pdflatex")
;; always autosave
(setq TeX-save-query nil)
;; In AUCTex, make PDF by default (can toggle with C-c C-t C-p)
(add-hook 'LaTeX-mode-hook '(lambda () (TeX-PDF-mode 1)))
#+end_src

And... AucTex does not automatically support nomencalture so (from [https://tex.stackexchange.com/questions/36582/using-nomenclature-and-emacs])
#+begin_src emacs-lisp
;; nomenclature for latex
(eval-after-load "tex"
  '(add-to-list 'TeX-command-list
                '("Nomenclature" "makeindex %s.nlo -s nomencl.ist -o %s.nls"
                  (lambda (name command file)
                    (TeX-run-compile name command file)
                    (TeX-process-set-variable file 'TeX-command-next TeX-command-default))
                  nil t :help "Create nomenclature file")))
#+end_src

Weird behavior with AucTex (elsewhere?) where creating a double ~''~ replaces
the previous closing bracket with quotes?? (**NB** this does not really work)
#+begin_src emacs-lisp
(setq TeX-quote-after-quote nil)
#+end_src

#+begin_src emacs-lisp
(map!
 :after tex
 :map TeX-mode-map
 :leader
      (:prefix "m"
        :desc "Insert citation" "i"  #'helm-bibtex-with-local-bibliography
        :desc "Reftex citation" "r"  #'reftex-citation
        ;:desc "figlet" "f" #("figlet")
        ;:desc "text" "f f" #'figlet
        ;:desc "comment" "f c" #'figlet-comment
        ))
#+end_src

Convert bibtex entries to Title Case, from
http://kitchingroup.cheme.cmu.edu/blog/2014/10/12/Title-casing-bibtex-entry-journal-titles/

To use, put this at beginning of bibtex file
#+begin_example
% (bibtex-map-entries 'jmax-title-case-article)
#+end_example
Place cursor at line and ~C-x C-e~

#+begin_src emacs-lisp
(defvar jmax-lower-case-words
  '("a" "an" "on" "and" "for"
    "the" "of" "in")
  "List of words to keep lowercase")

(defvar entry-types
  '("article" "journal" "book" "misc" "techreport" "inproceedings" "phdthesis")
  "List of bib entry types")

(defun jmax-title-case-article (&optional key start end)
  "Convert a bibtex entry article title to title-case. The
arguments are optional, and are only there so you can use this
function with `bibtex-map-entries' to change all the title
entries in articles."
  (interactive)
  (bibtex-beginning-of-entry)

  (let* ((title (bibtex-autokey-get-field "title"))
         (words (split-string title))
         (lower-case-words '("a" "an" "on" "and" "for"
                             "the" "of" "in")))
    (when
        ;(string= "article" (downcase (cdr (assoc "=type=" (bibtex-parse-entry)))))
        (-contains? entry-types (downcase (cdr (assoc "=type=" (bibtex-parse-entry)))))
      (setq words (mapcar
                   (lambda (word)
                     (if (or
                          ;; match words containing {} or \ which are probably
                          ;; LaTeX or protected words
                          (string-match "\\$\\|{\\|}\\|\\\\" word)
                          ;; these words should not be capitalized, unless they
                          ;; are the first word
                          (-contains? lower-case-words (s-downcase word)))
                         word
                       (s-capitalize word)))
                   words))

      ;; Check if first word should be capitalized
      (when (-contains? jmax-lower-case-words (car words))
        (setf (car words) (s-capitalize (car words))))

      ;; this is defined in doi-utils
      (bibtex-set-field
       "title"
       (mapconcat 'identity words " "))
      (bibtex-fill-entry))))
#+end_src

Tex word count with master file (from
[https://superuser.com/questions/125027/word-count-for-latex-within-emacs])
#+begin_src emacs-lisp
(defun latex-word-count-master ()
  (interactive)
  (if (eq TeX-master t)
      (setq master (buffer-file-name))
    (setq master (concat (expand-file-name TeX-master) ".tex")))
  (shell-command (concat "texcount "
                         "-dir "
                         "-unicode "
                         "-inc "
                         master)))
#+end_src

Also seems that AucTex resets the ~delete-selection-mode~
#+begin_src emacs-lisp
;(add-hook 'LaTeX-mode-hook '(lambda () (setq delete-selection-mode t)))
(eval-after-load "tex"
  '(progn
     '(setq delete-selection-mode t)

   '(setq TeX-complete-list
        (append '(
                  ("\\\\refsect{\\([^{}\n
\\%,]*\\)" 1 LaTeX-label-list "}")
                  ) TeX-complete-list))
 '(setq TeX-complete-list
        (append '(
                  ("\\\\refchap{\\([^{}\n
\\%,]*\\)" 1 LaTeX-label-list "}")
                  ) TeX-complete-list))
 '(setq TeX-complete-list
        (append '(
                  ("\\\\refig{\\([^{}\n
\\%,]*\\)" 1 LaTeX-label-list "}")
                  ) TeX-complete-list))
 '(setq TeX-complete-list
        (append '(
                  ("\\\\eqn{\\([^{}\n
\\%,]*\\)" 1 LaTeX-label-list "}")
                  ) TeX-complete-list))
  ))
#+end_src
#+begin_src emacs-lisp
(add-hook 'LaTeX-mode-hook '(lambda () (global-set-key (kbd "C-e") 'move-end-of-line)))
#+end_src

#+begin_src emacs-lisp

#+end_src
** EIN

** Jupyter-emacs
*** Spyder-like experience

#+begin_src emacs-lisp
(set-popup-rule! "^\\*Python" :side 'right :width 0.5)
#+end_src

Tell jupyter emacs to send code to repl
#+begin_src emacs-lisp
(setq jupyter-repl-echo-eval-p t)
;(setq conda-anaconda-home "~/opt/miniconda3")
#+end_src

#+begin_src emacs-lisp
;; (use-package conda
;;   :defer t
;;   :init
;;   (setq conda-anaconda-home (expand-file-name "~/opt/miniconda3")
;;         conda-env-home-directory (expand-file-name "~/opt/miniconda3")))
#+end_src

Send code between ~#%%~ pairs or end of file
#+begin_src emacs-lisp
(defun jupyter-send-cell()
  (interactive)
  (save-excursion
  (if (not (search-backward "#%%" nil t))
        (message "Not in a cell")
      (forward-line)
      (beginning-of-line)
      (set-mark (point))

      (if (not (search-forward "#%%" nil t))
          (end-of-buffer))
      (goto-char (point))
      (activate-mark)
      (jupyter-eval-string (buffer-substring (mark) (point)))
      (deactivate-mark)
      )))
#+end_src

Key bindings
#+begin_src emacs-lisp
(with-eval-after-load 'python-mode
  (define-key python-mode-map (kbd "<C-return>") 'jupyter-send-cell)
)
#+end_src

#+begin_src emacs-lisp
;; (defun display-new-buffer (buffer force-other-window)
;;   "If BUFFER is visible, select it.
;; If it's not visible and there's only one window, split the
;; current window and select BUFFER in the new window. If the
;; current window (before the split) is more than 100 columns wide,
;; split horizontally(left/right), else split vertically(up/down).
;; If the current buffer contains more than one window, select
;; BUFFER in the least recently used window.
;; This function returns the window which holds BUFFER.
;; FORCE-OTHER-WINDOW is ignored."
;;   (or (get-buffer-window buffer)
;;     (if (one-window-p)
;;         (let ((new-win
;;                (if (> (window-width) 100)
;;                    (split-window-horizontally)
;;                  (split-window-vertically))))
;;           (set-window-buffer new-win buffer)
;;           new-win)
;;       (let ((new-win (get-lru-window)))
;;         (set-window-buffer new-win buffer)
;;         new-win))))
;; ;; use display-buffer-alist instead of display-buffer-function if the following line won't work
;; (setq display-buffer-function 'display-new-buffer)
#+end_src

#+begin_src emacs-lisp
(defun toggle-window-split ()
  (interactive)
    (if (= (count-windows) 2)
      (let* ((this-win-buffer (window-buffer))
            (next-win-buffer (window-buffer (next-window)))
            (this-win-edges (window-edges (selected-window)))
            (next-win-edges (window-edges (next-window)))
            (this-win-2nd
             (not (and (<= (car this-win-edges)
                        (car next-win-edges))
                    (<= (cadr this-win-edges)
                        (cadr next-win-edges)))))
         (splitter
          (if (= (car this-win-edges)
                 (car (window-edges (next-window))))
              'split-window-horizontally
            'split-window-vertically)))
    (delete-other-windows)
    (let ((first-win (selected-window)))
      (funcall splitter)
      (if this-win-2nd (other-window 1))
      (set-window-buffer (selected-window) this-win-buffer)
      (set-window-buffer (next-window) next-win-buffer)
      (select-window first-win)
      (if this-win-2nd (other-window 1))))))

(defun jupyter-repl-associate-buffer-side ()
    (interactive)
    (call-interactively 'jupyter-repl-associate-buffer)
    (call-interactively 'toggle-window-split)
)

;(defun cazz (client)
;  (message "cazzo"))
;(advice-add 'jupyter-repl-associate-buffer :after 'cazz) ;toggle-window-split)
;(setq split-height-threshold nil)
;(setq split-width-threshold 0)
#+end_src

** C++
#+begin_src emacs-lisp
(after! projectile
  (projectile-register-project-type 'cmake '("CMakeLists.txt")
                                  :project-file "CMakeLists.txt"
                                  :compilation-dir "build"
                                  :configure "cmake %s -B %s"
                                  :compile "cmake ..; make -j4"
                                  :test "ctest"
                                  :install "cmake --build . --target install"
                                  :package "cmake --build . --target package")
  )
#+end_src

#+begin_src emacs-lisp

(use-package lsp-mode
  :config
  (setq lsp-vetur-format-options-tab-size 4)
  ;(setq lsp-vetur-format-enable nil)
  (setq lsp-prompt-projet-root t)
  (setq lsp-auto-guess-root t)
)

(require 'realgud-lldb)

;; clang-format
(use-package clang-format
	:ensure t
	:bind (("C-c f b" . clang-format-buffer)
				 ("C-c f r" . clang-format-region))
	:hook (before-save . (lambda ()
												 (when (derived-mode-p 'c-mode 'c++-mode)
													 (clang-format-buffer))))
	:custom
	(clang-format-style "file")
	;(clang-format-fallback-style "")
    ;https://zed0.co.uk/clang-format-configurator/
    (clang-format-fallback-style "none")
    )

(setq c-basic-offset 2)
 ;; (clang-format-fallback-style
 ;;         "{BasedOnStyle: google, AlignConsecutiveAssignments: true, BinPackArguments: true, BinPackParameters: true, AlignAfterOpenBracket: true, TabWidth: 4}")
(defun my-c++-mode-hook ()
  (setq indent-tabs-mode t
		tab-width 2
		c-basic-offset 2))
(add-hook 'c++-mode-hook 'my-c++-mode-hook)

;; DAP THIS
(use-package dap-mode
 :config
 (dap-mode 1)
 (require 'dap-hydra)
(require 'dap-launch)
 (require 'dap-lldb)	; download and expand lldb-vscode to the =~/.extensions/webfreak.debug= ;gdb-lldb
; (use-package dap-lldb
 ; :disabled t)
 (use-package dap-ui
   :ensure nil
   :config
   (dap-ui-mode 1)))

;; (add-hook! 'gud-mode-hook
;;            #'company-mode)
;; (require 'gud-lldb)

;; (use-package dap-mode
;;   :ensure t
;;   :commands dap-mode
;;   :hook (dap-stopped . (lambda (arg) (call-interactively #'dap-hydra)))
;;   :config
;;   (dap-mode 1)
;;   (require 'dap-ui)
;;   (dap-ui-mode 1)
;;   (require 'dap-lldb)
;;   (setq dap-lldb-debug-program "/Users/colormotor/.vscode/extensions/lanza.lldb-vscode-0.2.2/bin/darwin/bin/lldb-vscode"))
#+end_src
