#+TITLE: Emacs Doom Config
#+AUTHOR: Daniel Berio
#+EMAIL: drand48@gmail.com
#+LANGUAGE: en
#+STARTUP: inlineimages
#+PROPERTY: header-args :tangle yes :cache yes :results silent :padline no

To execute all and update use ~C-c C-v b~ or ~C-c C-v C-b~ or ~M-x
org-babel-execute-buffer~
Or ~M-x doom/reload~

**NB.** For a literate config to work you need to set the ~literate~ flag in ~init.el~

** General
Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.

#+begin_src emacs-lisp
(setq user-full-name "Daniel Berio"
      user-mail-address "drand48@gmail.com")
#+end_src

Start emacs with a maximized window
#+begin_src emacs-lisp
;(add-hook 'window-setup-hook 'toggle-frame-maximized t)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src
** Figlet
Because I like ascii text. From [https://github.com/emacsmirror/figlet/blob/master/figlet.el]
Type ~M-x figlet~ and you will be asked for a string. If you use a prefix ~C-u
M-x figlet~ it will ask for a font.
#+begin_src emacs-lisp
(load! "~/.doom.d/figlet/figlet.el")
(setq figlet-font-dir "~/.doom.d/figlet/fonts")
(setq figlet-default-font "computer")
#+end_src

** Editor
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

#+begin_src emacs-lisp
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
#+end_src

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:

#+begin_src emacs-lisp
;(setq doom-font (font-spec :family "monospace" :size 14))
(setq doom-font (font-spec :family "Fira Code" :size 13))
#+end_src


There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
~load-theme~~ function. This is the default:

#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src


This determines the style of line numbers in effect. If set to ~nil~, line
numbers are disabled. For relative line numbers, set this to ~relative~.
#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src


*** Key-bindings etc
#+begin_src emacs-lisp
; (evil-multiedit-default-keybinds)
#+end_src

#+begin_src emacs-lisp
(global-set-key (kbd "C-y") 'yank)
(global-set-key (kbd "s-z") 'undo-tree-undo)
(global-set-key (kbd "s-Z") 'undo-tree-redo)
(global-set-key (kbd "s-v") 'yank)
(global-set-key (kbd "s-c") 'evil-yank)
(global-set-key (kbd "s-a") 'mark-whole-buffer)
(global-set-key (kbd "s-x") 'kill-region)
(global-set-key (kbd "s-s") 'save-buffer)

#+end_src

Counsel: Use ~SPC-~~ followed by char

#+begin_src emacs-lisp
;; (map! :leader
;;       (:prefix "m"
;;         :desc "Ivy citation" "i"  #'ivy-bibtex-with-local-bibliography
;;         :desc "Reftex citation" "r"  #'reftex-citation
;;         ;:desc "figlet" "f" #("figlet")
;;         ;:desc "text" "f f" #'figlet
;;         ;:desc "comment" "f c" #'figlet-comment
;;         ))
#+end_src

Some key bindings I am used to, but this is not working in Doom...
#+begin_src emacs-lisp
;; Use C-u, C-d also in insert mode
(global-set-key (kbd "C-u") nil)
(global-set-key (kbd "C-d") nil)
(global-set-key (kbd "C-u") 'evil-scroll-up)
(global-set-key (kbd "C-d") 'evil-scroll-down)
(global-set-key (kbd "C-e") 'move-end-of-line)
#+end_src

Always support shift selec and delete
#+begin_src emacs-lisp
;; Delete selection
(setq delete-selection-mode t)
(setq shift-select-mode t)
#+end_src

Windmove:
#+begin_src emacs-lisp
(global-set-key (kbd "<s-left>")  'windmove-left)
(global-set-key (kbd "<s-right>") 'windmove-right)
(global-set-key (kbd "<s-up>")    'windmove-up)
(global-set-key (kbd "<s-down>")  'windmove-down)
#+end_src
*** Look and feel
#+begin_src emacs-lisp
(use-package! dimmer
  :config (dimmer-mode))
#+end_src
** Notes from doom config
Here are some additional functions/macros that could help you configure Doom:

 - ~load!~ for loading external *.el files relative to this one
 - ~use-package~ for configuring packages
 - ~after!~ for running code after a package has loaded
 - ~add-load-path!~ for adding directories to the `load-path', relative to
   this file. Emacs searches the ~load-path~ when you load packages with
   ~require~ or ~use-package~.
 - ~map!~ for binding new keys

 To get information about any of these functions/macros, move the cursor over
 the highlighted symbol at press 'K' (non-evil users must press 'C-c g k').
 This will open documentation for it, including demos of how they are used.


You can also try ~gd~ (or ~C-c g d~) to jump to their definition and see how
they are implemented.

** Org mode customizations

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org ~loads!~

#+begin_src emacs-lisp
(setq org-directory "~/Dropbox/org/")
#+end_src

Enable shift select in org mode
#+BEGIN_SRC emacs-lisp
(setq org-support-shift-select 'always)
#+END_SRC

Embed CSS by default
#+begin_src emacs-lisp
(defun my-org-inline-css-hook (exporter)
  "Insert custom inline css"
  (when (eq exporter 'html)
    (let* ((dir (ignore-errors (file-name-directory (buffer-file-name))))
           (path (concat dir "style.css"))
           (homestyle (or (null dir) (null (file-exists-p path))))
           (final (if homestyle "~/.doom.d/org-style.css" path))) ;; <- set your own style file path
      (setq org-html-head-include-default-style nil)
      (setq org-html-head (concat
                           "<style type=\"text/css\">\n"
                           "<!--/*--><![CDATA[/*><!--*/\n"
                           (with-temp-buffer
                             (insert-file-contents final)
                             (buffer-string))
                           "/*]]>*/-->\n"
                           "</style>\n")))))

(add-hook 'org-export-before-processing-hook 'my-org-inline-css-hook)
#+end_src

Setup org-ref

#+begin_src emacs-lisp

;; Big hack to insert biblio entry titles
;; unelegant simply because I do not really know LISP
;; adapted from: http://www.mail-archive.com/emacs-orgmode@gnu.org/msg110385.html

(defun set-format (key)
  (setf (cdr (assoc key (cdr (assoc "org"
                                    org-ref-formatted-citation-formats))))
        "${author} ${year}. /${title}/. [[cite:${=key=}]]")
  )

(def-package! org-ref
    :after org
    :init
    ; code to run before loading org-ref
    :config
    ; code to run after loading org-ref
    (setq org-ref-default-bibliography '("./autograff-biblio.bib")) ; this is a list but multiple files don't seem to work

    (setq org-ref-formatted-citation-backend "org")
    (set-format "article")
    (set-format "inproceedings")
    (set-format "book")
    (set-format "phdthesis")
    (set-format "inbook")
    (set-format "incollection")
    (set-format "proceedings")
    (set-format "unpublished")

    )
#+end_src

Setup org to open Zotero links
#+BEGIN_SRC emacs-lisp
;; Create hyperlink on export
(defun zotero-org-export (link description format)
  (let ((path (concat "zotero:" link))
        (desc (or description "Open in Zotero")))
    (pcase format
      (`html (format "<a target=\"_blank\" href=\"%s\">%s</a>" path desc))
      (`latex (format "\\href{%s}{%s}" path desc))
      (`texinfo (format "@uref{%s,%s}" path desc))
      (`ascii (format "%s (%s)" desc path))
      (t path))))
;; Setup links
(add-hook 'org-mode-hook
          (lambda ()
(org-add-link-type "zotero"
                   (lambda (path)
                              (browse-url (concat "zotero:" path)))
                   'zotero-org-export)))
#+END_SRC

Preview latex on save ([[https://emacs.stackexchange.com/questions/38198/automatically-preview-latex-in-org-mode-as-soon-as-i-finish-typing][from]])
#+begin_src emacs-lisp
(defun my/org-render-latex-fragments ()
  (if (org--list-latex-overlays)
      (progn (org-toggle-latex-fragment)
             (org-toggle-latex-fragment))
    (org-toggle-latex-fragment)))

(add-hook 'org-mode-hook
          (lambda ()
            (add-hook 'after-save-hook 'my/org-render-latex-fragments nil 'make-the-hook-local)))
#+end_src
Counsel key-bindings
#+begin_src emacs-lisp
(map!
 :after org
 :map org-mode-map
 :leader
      (:prefix "m"
        :desc "Insert citation" "i"  #'org-ref-helm-insert-cite-link
        ))
#+end_src

Also org mode resets the ~delete-selection-mode~. TODO find a better solution to this
#+begin_src emacs-lisp
(add-hook 'org-mode-hook '(lambda () (setq delete-selection-mode t)))
#+end_src

** Latex (AucTex + RefTex)


And set pdf-tools internal latex viewer

#+begin_src emacs-lisp
(setq +latex-viewers '(pdf-tools))
#+end_src

From doom issues, sync latex and pdf, still bit dodgy:
#+begin_src emacs-lisp
;; to use pdfview with auctex
 (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
    TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
    TeX-source-correlate-start-server t) ;; not sure if last line is neccessary
#+end_src


Trying to get rid of the ~epdfinfo: Destination not found~ error.
See [https://github.com/politza/pdf-tools/issues/302]
#+begin_src emacs-lisp
(add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
#+end_src

Ask for master file (~Tex-master~ multifile support)? Ideally we would want
AucTex to always ask (~nil~), but this is set in the local variables of a buffer
(~C-c n~ to reset). Also seems that manually setting the variable (at the end of
the doc) does not work, so it needs to be done with ~C-c _~ at least on Mac.
#+begin_src emacs-lisp
(add-hook 'LaTeX-mode-hook
          (setq-default TeX-master t))
#+end_src

Get RefTex to search for valid biblios
#+begin_src emacs-lisp
(setq reftex-use-external-file-finders t)
#+end_src

Setting up IVY bibtex
#+begin_src emacs-lisp
;(setq ivy-bibtex-default-action 'ivy-bibtex-insert-key)
#+end_src

When Option-clicking on text, jump to pdf position.
#+begin_src emacs-lisp
(with-eval-after-load "latex"
  (define-key LaTeX-mode-map [s-down-mouse-1] 'pdf-sync-forward-search))
#+end_src

#+begin_src emacs-lisp
;; Using pdflatex as the default compiler for .tex files
(setq latex-run-command "pdflatex")
;; always autosave
(setq TeX-save-query nil)
;; In AUCTex, make PDF by default (can toggle with C-c C-t C-p)
(add-hook 'LaTeX-mode-hook '(lambda () (TeX-PDF-mode 1)))
#+end_src
Also seems that AucTex resets the ~delete-selection-mode~
#+begin_src emacs-lisp
(add-hook 'LaTeX-mode-hook '(lambda () (setq delete-selection-mode t)))
#+end_src
#+begin_src emacs-lisp
(add-hook 'LaTeX-mode-hook '(lambda () (global-set-key (kbd "C-e") 'move-end-of-line)))
#+end_src
And... AucTex does not automatically support nomencalture so (from [https://tex.stackexchange.com/questions/36582/using-nomenclature-and-emacs])
#+begin_src emacs-lisp
;; nomenclature for latex
(eval-after-load "tex"
  '(add-to-list 'TeX-command-list
                '("Nomenclature" "makeindex %s.nlo -s nomencl.ist -o %s.nls"
                  (lambda (name command file)
                    (TeX-run-compile name command file)
                    (TeX-process-set-variable file 'TeX-command-next TeX-command-default))
                  nil t :help "Create nomenclature file")))
#+end_src

Weird behavior with AucTex (elsewhere?) where creating a double ~''~ replaces
the previous closing bracket with quotes?? (**NB** this does not really work)
#+begin_src emacs-lisp
(setq TeX-quote-after-quote nil)
#+end_src

#+begin_src emacs-lisp
(map!
 :after tex
 :map TeX-mode-map
 :leader
      (:prefix "m"
        :desc "Insert citation" "i"  #'helm-bibtex-with-local-bibliography
        :desc "Reftex citation" "r"  #'reftex-citation
        ;:desc "figlet" "f" #("figlet")
        ;:desc "text" "f f" #'figlet
        ;:desc "comment" "f c" #'figlet-comment
        ))
#+end_src

Convert bibtex entries to Title Case, from
http://kitchingroup.cheme.cmu.edu/blog/2014/10/12/Title-casing-bibtex-entry-journal-titles/

To use, put this at beginning of bibtex file
#+begin_example
% (bibtex-map-entries 'jmax-title-case-article)
#+end_example
Place cursor at line and ~C-x C-e~

#+begin_src emacs-lisp
(defvar jmax-lower-case-words
  '("a" "an" "on" "and" "for"
    "the" "of" "in")
  "List of words to keep lowercase")

(defvar entry-types
  '("article" "journal" "book" "misc" "techreport" "inproceedings" "phdthesis")
  "List of bib entry types")

(defun jmax-title-case-article (&optional key start end)
  "Convert a bibtex entry article title to title-case. The
arguments are optional, and are only there so you can use this
function with `bibtex-map-entries' to change all the title
entries in articles."
  (interactive)
  (bibtex-beginning-of-entry)

  (let* ((title (bibtex-autokey-get-field "title"))
         (words (split-string title))
         (lower-case-words '("a" "an" "on" "and" "for"
                             "the" "of" "in")))
    (when
        ;(string= "article" (downcase (cdr (assoc "=type=" (bibtex-parse-entry)))))
        (-contains? entry-types (downcase (cdr (assoc "=type=" (bibtex-parse-entry)))))
      (setq words (mapcar
                   (lambda (word)
                     (if (or
                          ;; match words containing {} or \ which are probably
                          ;; LaTeX or protected words
                          (string-match "\\$\\|{\\|}\\|\\\\" word)
                          ;; these words should not be capitalized, unless they
                          ;; are the first word
                          (-contains? lower-case-words (s-downcase word)))
                         word
                       (s-capitalize word)))
                   words))

      ;; Check if first word should be capitalized
      (when (-contains? jmax-lower-case-words (car words))
        (setf (car words) (s-capitalize (car words))))

      ;; this is defined in doi-utils
      (bibtex-set-field
       "title"
       (mapconcat 'identity words " "))
      (bibtex-fill-entry))))
#+end_src
